### ISSUE TITLE
Update Tesseract Libs

### ISSUE THREAD

**Issue by hactar** [SwiftyTesseract/SwiftyTesseract#10]
According to the logs, 4.0.0-beta.1 is included with SwiftTesseract - the latest version appears to be beta 4. 

I've tried playing with the build scripts from g8, but can't get it to build on my machine, so an update would be greatly appreciated.

**Comment by Steven0351** [comment]
This is actually on my list of to-do’s. The build scripts from g8 took a bit of “massaging” on my end to get them to work with the latest releases. I’ll try and get something merged this week.

**Comment by hactar** [comment]
Awesome, thanks!

**Comment by Steven0351** [comment]
#11 Addresses this with along with a major version update. This will only affect you if you were using the `CustomData` enum, which has been combined with `RecognitionLanguage` as a single case (`.custom(String)`), and is only compatible with Swift 4.2.
