### ISSUE TITLE
ARM64 and Cocoapods

### ISSUE THREAD

**Issue by advatar** [SwiftyTesseract/SwiftyTesseract#100]
### Checklist
- [x] I've read the [Readme](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/README.md)
- [x] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [x] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).
- [x] I'm using Cocoapods 1.11.2 for dependency management
- [] I'm using Carthage  for dependency management

**Describe the bug**

could not find module 'SwiftyTesseract' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64, at: /Users/johansellstrom/Library/Developer/Xcode/DerivedData/iD-gqclcoagmgiqyibufudyaxyxvdfl/Build/Products/Debug-iphonesimulator/SwiftyTesseract/SwiftyTesseract.framework/Modules/SwiftyTesseract.swiftmodule

**Sample Code**
In Podfile: pod 'SwiftyTesseract'
**Expected behavior**
libtesseract built for ARM64
**Versions**
* Xcode: 13.1 (13A1030d)
* Swift:5
* iOS:12.0.1
* SwiftyTesseract:3.1.3

**Additional context**
It seems that the podspec for 4.0.1 has not been published why you get 3.1.3 instead. Actually SwiftyTesseract.podspec is no longer in the current branch.

**Comment by Steven0351** [comment]
As per the readme, I've dropped support for cocoapods. You can give https://github.com/kurzdigital/kta-tesseract-swift a try
