### ISSUE TITLE
CocoaPods support for v4+

### ISSUE THREAD

**Issue by Mattijah** [SwiftyTesseract/SwiftyTesseract#101]
Hi there!

Is there any plan or would it be possible as a feature request to add a CocoaPods support back for v4 and newer?

Thanks

**Comment by Steven0351** [comment]
There is no plan to support Cocoapods again. It’s an additional maintenance burden to support multiple package managers. There is https://github.com/kurzdigital/kta-tesseract-swift if you need cocoapods support

**Comment by Mattijah** [comment]
Does it really take as much effort? I don't have similar experience with all honesty. You've dropped support of CocoaPods, which doesn't only affect libraries using and being dependant on `SwiftyTesseract`, but also other users if these libs drop CocoaPods support too because of this.

**Comment by Steven0351** [comment]
It’s an additional maintenance and support burden. It requires building and vending binary dependencies that increases the size of the repository and I personally don’t feel like dealing with it. This is open source software, so if it’s not meeting your needs, or if my direction conflicts with yours, I encourage you to fork the project. I made a very purposeful decision in only supporting the Swift Package Manager.
