### ISSUE TITLE
Fix building of the lib on the Xcode 10 and Swift 4.2

### ISSUE THREAD

**Issue by GaevYuriy** [SwiftyTesseract/SwiftyTesseract#13]
<img width="1211" alt="2018-09-28 9 46 50" src="https://user-images.githubusercontent.com/23167917/46195035-6e70bb00-c303-11e8-9a9f-3401d488ba63.png">

**Comment by Steven0351** [comment]
Check that your Xcode 10 project is using Swift 4.2 and not Swift 4; `img.pngData()` was announced at WWDC in the “What’s new in Cocoa Touch” talk for Swift 4.2

**Comment by Steven0351** [comment]
I just tested this on a fresh Xcode 10 project using Swift 4.2 with no issues. If you continue having issues, re-open this issue and post a screen shot of the Swift version you are using from the Xcode settings and I’ll look into it. Between not having any issues compiling against Xcode 10 and Swift 4.2 both locally on my machine and on Travis CI, I’m determining that this is an issue with the Swift version of your Xcode project and not the library.
