### ISSUE TITLE
read_params_file: parameter not found: enable_new_segsearch

### ISSUE THREAD

**Issue by karsil** [SwiftyTesseract/SwiftyTesseract#14]
First of all: Thanks for your work!

I´ve encountered the following problem after selecting an UIImage and trying to run SwiftyTesseract:

```swift
func performImageRecognition(_ image: UIImage) {
    print("performImageRecognition() called, setting language...")
    let swiftyTesseract = SwiftyTesseract(languages: [.english])
    print("performOCR()...")
    
    swiftyTesseract.performOCR(on: image) { (recognizedString) in
        print("performOCR done...")
        guard let recognizedString = recognizedString else { return }
        print(recognizedString)
    }
    print("recognition done")
}
```

When executing I got the following error:
```
performImageRecognition() called, setting language...
read_params_file: parameter not found: enable_new_segsearch
```
After that line, the app crashes. I haven´t found a solution until now. Does someone has an idea?

Thanks in advance!

**Comment by Steven0351** [comment]
I won’t be able to check this on my machine for a few hours, but do you have your language training data in a folder named “tessdata” in your main bundle as a folder reference (blue folder icon)? Also, what version of SwiftyTessersct are you using?

**Comment by karsil** [comment]
> I won’t be able to check this on my machine for a few hours, but do you have your language training data in a folder named “tessdata” in your main bundle as a folder reference (blue folder icon)? Also, what version of SwiftyTessersct are you using?

"tessdata" folder is there and filled. The used version of SwiftyTesseract is 1.0.

**Comment by Steven0351** [comment]
Are you’re using Xcode 10 and Swift 4.2? If so, try version 2.0

**Comment by karsil** [comment]
> Are you’re using Xcode 10 and Swift 4.2? If so, try SwiftyTessersct 2.0

I do actually ! I´ll give it a try and update you.

**Comment by Steven0351** [comment]
I copied and pasted your function into a fresh Xcode project using Xcode 10, Swift 4.2, and SwiftyTesseract 2.0 and everything worked as expected. Let me know if bumping up the version of SwiftyTesseract worked out for you.

**Comment by karsil** [comment]
Tried it, message still pops up...

Made a simple app to show the error:
https://github.com/karsil/iOS_example_OCR

Rest of the code is based on this tutorial:
https://www.raywenderlich.com/306-tesseract-ocr-tutorial-for-ios

**Comment by Steven0351** [comment]
I’ll pull your example project and run, but the tutorial you’re following uses a library that uses tesseract 3.0, while SwiftyTesseract uses tesseract 4.0 under the hood and makes no use of the cube files.

**Comment by karsil** [comment]
Found the problem: I´ve used the `tessdata` of the tutorial and not the one from the SwiftyTesseract README. After changing it (in my example `tessdata_fast`), the error was gone and OCR has been successfully performed.

Issue closed, thank you very mich for your time!
