### ISSUE TITLE
Failed loading language 'eng'.

### ISSUE THREAD

**Issue by hunterteck** [SwiftyTesseract/SwiftyTesseract#15]
Hello!
I have problem with SwiftyTesseract initialization. When I'm trying to init i get the error:

Error opening data file /Users/*username*/Library/Developer/CoreSimulator/Devices/399FC739-54D5-49C1-8F97-06962AA2B028/data/Containers/Bundle/Application/306FED96-9738-477C-922D-2ACA51AFC8D7/*app name*/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

I've downloaded tessdata from links which you provided. Also I added folder tessdata to the project and put into it correct trained data. I have no ideas how to solve it, but my previous experience with [Gali8 Tessecact wrapper](https://github.com/gali8/Tesseract-OCR-iOS) was fine.

I'm using XCode 10, iOS simulator and SwiftyTesseract v.2.0

**Comment by Steven0351** [comment]
Is your tessdata folder icon blue or yellow?

**Comment by hunterteck** [comment]
Blue.

**Comment by Steven0351** [comment]
Please paste your implementation and advise if you are implementing it in your primary bundle or another bundle. If you are implanting SwiftyTessersct in another bundle then you have to pass the bundle to the initializer. The Travis build has no issues or errors building and running library so it’s extremely likely it’s a configuration issue

**Comment by hunterteck** [comment]
I've just created test project. Then I configured it to use SwiftyTesseract, ran it and it worked fine. 
This is magic. Thanks for help. I will try to solve this configuration issue.

**Comment by Steven0351** [comment]
No problem! Please feel free to open up any other issues if you run into trouble

**Comment by hunterteck** [comment]
I found out the reason why it doesn't work. My test project is named TestTesseract and it works well.
The name of my current project contains whitespace symbol. It looks like *BLABLA BLABLA*. 
Then I changed in test project target name to Test Tesseract(whitespace in name) and SwiftyTesseract doesn't work - Error opening data file /var/containers/Bundle/Application/816539EB-044E-4DBA-9DD0-277DF73C3F09/Test%20Tesseract.app/tessdata/eng.traineddata. I spent a day and half to solve it :(

**Comment by Steven0351** [comment]
Interesting. This may have to do with how environment variables are read from iOS in Tesseract itself, which happens at the OS level and is of the hands of the library itself. However I’ll look into it and see if there is anything I can do

**Comment by Steven0351** [comment]
Unbeknownst to me, using `URL.absoluteString` adds percent encoding to the string (the cause of the %20 you saw inserted where your spaces were). Obviously this would be good if you were creating a URL that would be meant for the web, but it obviously does not do too well when locating files on a device. I've never created a target with spaces, and is also impossible to test without changing my target names themselves, but I was able to get this working on a fresh project with a target that contained spaces in its name. Make sure to update your pod and let me know how it fares!
