### ISSUE TITLE
Pod install: Error installing SwiftyTesseract

### ISSUE THREAD

**Issue by OffensivelyBad** [SwiftyTesseract/SwiftyTesseract#17]
After adding `pod 'SwiftyTesseract'` to my podfile and trying pod install with CocoaPods version 1.5.3, I get the following error message:

`[!] Unable to find a specification for `SwiftyTesseract`

**Comment by Steven0351** [comment]
Please refer to issue #7, it’s likely that your local spec repo has not been updated.

**Comment by OffensivelyBad** [comment]
Thanks @Steven0351 .  Running `pod setup` after updating cocoapods solved it.

**Comment by Steven0351** [comment]
Also, I believe `pod repo update` will do the same
