### ISSUE TITLE
Default config of Tesseract unable to read number-only images

### ISSUE THREAD

**Issue by Jeehut** [SwiftyTesseract/SwiftyTesseract#19]
Hi and thank you for this great wrapper around Tesseract. I've successfully used this library to scan sparse text on websites. I've even written tests to optimize the accuracy of text detection and succeeded in reaching an accuracy of 98.3% on German text. But there is one specific issue which must be a Tesseract configuration problem, because the image quality of the data is great and values are sometimes read perfectly fine but sometimes it just doesn't read anything. I mean nothing, not even a single number!

Here are a few example year numbers that I can't read:
![1923](https://user-images.githubusercontent.com/6942160/51044721-16b04400-15c2-11e9-8efa-9ea2133d7f1c.png)
![1948](https://user-images.githubusercontent.com/6942160/51044722-16b04400-15c2-11e9-9db8-9e35ef56aee2.png)
![1960](https://user-images.githubusercontent.com/6942160/51044723-16b04400-15c2-11e9-8085-396359ea73ef.png)

The behavior is really weird, it's like flickering, sometimes it seems to accept the given as text and read it perfectly well. But most of the time it just seems to ignore the entire text ... as if it was no text to Tesseract just because it's a number.

I'm using the latest SwiftyTesseract, using this configuration:
```swift
SwiftyTesseract(languages: [.german, .english], engineMode: .lstmOnly)
```

The models are `tess_fast` in case you want to know, my preprocessing steps (color invert, contrast decrease, binarize) are based on GPUImage and give clear black text on white background results. 

My personal guess is, that [this line](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/6ed8b28c18496665cbd899a540df0e97428748c0/SwiftyTesseract/SwiftyTesseract/SwiftyTesseract.swift#L155) where you simply call `TessBaseAPIGetUTF8Text` is the problem. I can't find good documentation on Tesseract to prove this, but looking around [this line](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/6ed8b28c18496665cbd899a540df0e97428748c0/SwiftyTesseract/SwiftyTesseract/dependencies/include/tesseract/capi.h#L277) within the Tesseract header, it looks to me like `TessBaseAPIGetHOCRText`, `TessBaseAPIGetBoxText`, `TessBaseAPIGetUNLVText` and specifically `TessBaseAPIAllWordConfidences` could be useful to add as a configuration option to SwiftyTesseract. I'm not sure what these APIs do, but apparently `TessBaseAPIGetUTF8Text` isn't a good fit for reading years.  Or maybe there's a configuration option to fix this issue elsewhere?

Do you have any idea what the issue could be? I would gladly post a PR with an added configuration option if I was given any hint on where I can read the documentation about these methods. I couldn't find any ...

I read on StackOverflow somewhere that this could have to do with a wrong configuration of "page segmentation mode" in Tesseract. Specifically the recommendation for numbers is to use mode "13    Raw line". It would be great to have at least this as a configuration option.

**Comment by Steven0351** [comment]
Sorry for the delay in getting back to you about the issue. So, I just wrote tests using the images you provided and I was able to get the years back as results without issue. One of the images that I have in the test target bundle is actually an image with numbers only and I have never _personally_ had issues recognizing numbers only. I typically trim all of my Tesseract results using the String method `trimmingCharacters(in:)` to trim white spaces and newlines. As far as being digits only, I don't think that Tesseract really cares what kind of characters that it sees as long as it can be represented in UTF-8. The tests themselves use .traineddata files from the legacy tessdata repos so that blacklisting and whitelisting can be tested as well, so it could be possible that tessdata_fast isn't ideal in your scenario. Were the images you provided what is actually being generated when you are passing it to the library?

**Comment by Steven0351** [comment]
Using your preprocessed images, I was only able to recognize 1960. Using the non-processed images, I was unable to recognize 1923. Perusing the [Tesseract documentation](https://tesseract-ocr.github.io/4.0.0/index.html), the methods you referenced don't really appear to be optimal for the use of mobile OCR scanning. Unfortunately OCR is not 100% all of the time. With Tesseract, not only does the image quality matter, but font can matter in some cases as well. This has gotten better with Tesseract 4.0 over 3.05, but I'm inclined to agree with you that the Gaussian filter isn't helping with the numbers.

How are you feeding these images into Tesseract? Is the workflow to take a picture and then feed the static image into SwiftyTesseract or are you transforming CMSampleBuffers from an AVCaptureSession?

**Comment by Dschee** [comment]
> Perusing the Tesseract documentation, the methods you referenced don't really appear to be optimal for the use of mobile OCR scanning.

What do you mean by that? Which methods I referenced? I'm not getting really what you want to say with that statement. Do you mean, that the SwiftyTesseract methods currently in use are already optimal?

I know that it's not optimal and that font matters. I've even tried to train custom models using http://trainyourtesseract.com/ with the fonts the text is written in, but the overall recognition rate didn't improve at all, it even decreased, depending on the order of models I passed to SwiftyTesseract. I could remove the gaussian filter if that helps. I will add a Number-only test to my Unit Tests to ensure recognition isn't bad.

The latter, I'm receiving a CMSampleBuffer from an AVCAptureSession which I save to a variable called `sample` and then use this method when I press a button to start text recognition:

```swift
    func getCurrentImage() -> UIImage {
        let pixelBuffer = CMSampleBufferGetImageBuffer(sample!)
        let ciImage = CIImage(cvPixelBuffer: pixelBuffer!)
        return ciImage.toUIImage()!
    }
```

**Comment by Steven0351** [comment]
Sorry about the delayed response (pretty crazy week). The methods I was speaking of was in reference to the ones you mentioned you found:

> looking around this line within the Tesseract header, it looks to me like TessBaseAPIGetHOCRText, TessBaseAPIGetBoxText, TessBaseAPIGetUNLVText and specifically TessBaseAPIAllWordConfidences could be useful to add as a configuration option to SwiftyTesseract.

If you find those methods in the [Tesseract Documentation](
https://tesseract-ocr.github.io/4.0.0/index.htm), I think you'd likely agree. When I stated "the methods you referenced don't really appear to be optimal," I probably should have stated practical. For example, TessBaseAPIGetHOCRText makes an ["HTML-formatted string with hOCR markup from the internal data structures"](https://tesseract-ocr.github.io/4.0.0/a01625.html#ga7fffd7934197b7c9ac91db5aac09bf78), TessBaseAPIGetBoxText returns the ["recognized text ... as a char* which is coded in the same format as a box file used in training. Constructs coordinates in the original image - not just the rectangle"](https://tesseract-ocr.github.io/4.0.0/a01625.html#gaadda8cd6abe770d2f6a70a18329b1973), and TessBaseAPIGetUNLVText returns the ["recognized text ... as a char* which is coded as UNLV format Latin-1 with specific reject and suspect codes"](https://tesseract-ocr.github.io/4.0.0/a01625.html#ga173b4289191b6c2faf2a4a4b7c94affc).

However, I'm approaching this with the perspective of retrieving text from an image taken from the users camera; I'm not opposed to adding them to the SwiftyTesseract API, and I can see where TessBaseAPIAllWordConfidences could be useful for analyzing the confidence of the results, but most of those other methods seem to be more fit for OCR in a more traditional environment (e.g. document scanning).

In regards to your implementation, I do something similar but I don't return the results immediately. The particular implementation that I use is in the [SwiftyTesseractRTE repo](https://github.com/SwiftyTesseract/SwiftyTesseractRTE), but I determine the end result by feeding the SwiftyTesseract results into a data structure like this

```swift
struct RecognitionQueue<T: Hashable> {
  private var values: [T]
  
  let size: Int

  var allValuesMatch: Bool {
    guard size == values.count else { return false }
    return Set(values).count == 1
  }
  
  init(maxElements: Int) {
    size = maxElements
    values = [T]()
  }
  
  mutating func enqueue(_ value: T) {
    values.append(value)
    if values.count > size {
      dequeue()
    }
  }
  
  @discardableResult
  mutating func dequeue() -> T? {
    if values.isEmpty { return nil }
    return values.remove(at: 0)
  }
  
  mutating func clear() {
    values.removeAll()
  }

}
```
After I enqueue a result, I check the `allValuesMatch` property, and if it's true then I dequeue the result and use the dequeued value for presentation or whatever other operation may be performed. I usually find that using `RecognitionQueue` with a size of 3 usually serves me well.

**Comment by Dschee** [comment]
Thank you for the answer, I will have a look into SwiftyTesseractRTE sometime and report how that improves the recognition results. Please note that in the meantime I seem to mostly be able to recognize longer number texts, but still having problems single numbers.

**Comment by Steven0351** [comment]
One thing of note: if you take a look back at your unprocessed 1960, 1948, and 1923 image that you sent the second time around, the unprocessed image quality gradually got worse as you go from image to image. An issue that you may be coming across is camera autofocus not quite getting a good capture of the text you're trying to recognize, or it could be the light coming from the source (they appear to be taken from a screen) affecting how the lens is capturing the image. The method of buffering up the values like I do with `RecognitionQueue` helps with weeding out those "bad" CMSampleBuffers that may come in from the camera not receiving the most optimal capture. This obviously does come at the cost of not always getting a (nearly) immediate result as you probably do with your current implementation, but you do tend to end up with much more accurate results.

You may or may not want to use SwiftyTesseractRTE because it is heavy handed and would require you to conform to at least one protocol if you want to keep your current image processing implementation. You could probably pretty easily add something like `RecognitionQueue` into your existing implementation without much of a refactoring effort.

**Comment by GerfriedC** [comment]
I'm recently experiencing problems with the 3:
![IMG_2943 (2)](https://user-images.githubusercontent.com/36126252/95689474-4a922080-0c11-11eb-97c1-3e2322d4f7e9.jpg)

**Comment by Steven0351** [comment]
@GerfriedC Could you be a little more descriptive? What is it recognizing it as?

**Comment by GerfriedC** [comment]
> 
> 
> @GerfriedC Could you be a little more descriptive? What is it recognizing it as?

3 is recognized as 5 here  after an automatic clipping of a lower resolution image,
![grafik](https://user-images.githubusercontent.com/36126252/95713409-c8344b80-0c66-11eb-8c37-254eb0005b5e.png)
 I a  manually clipped high res image 3 stays 3 (alls with whitelist 0-9, OEM Tesseract Only V2.0.0.0 alpha 4.
Any hints?
many thanks

**Comment by Steven0351** [comment]
@GerfriedC nothing I can help you with there. The current version of Tesseract is 4.1.1 and this repository is wrapper for Tesseract to be used from the Swift language. You should first try installing the latest version of Tesseract for your OS and if you still have trouble, open an issue at the tesseract repository: https://github.com/tesseract-ocr/tesseract
