### ISSUE TITLE
Variable 'pixImage' passed by reference before being initialized

### ISSUE THREAD

**Issue by mihailsalari** [SwiftyTesseract/SwiftyTesseract#36]
Tried cocoapods installations and got this error:
![Screen Shot 2019-05-13 at 2 23 53 PM](https://user-images.githubusercontent.com/23311250/57617971-c6a2b780-758a-11e9-97e9-b37c110365dd.png)

**Comment by mihailsalari** [comment]
Interesting solution but not works...

**Comment by Steven0351** [comment]
I assume you are on Swift 5; the library is currently only compatible with Swift 4.2. An update is in the works

**Comment by mihailsalari** [comment]
Yes. I’ll change the language version. Thanks
