### ISSUE TITLE
Multi Thread

### ISSUE THREAD

**Issue by intellitour** [SwiftyTesseract/SwiftyTesseract#4]
Is there a way to accomplish multithread without having one instance per thread (operation)?

**Comment by Steven0351** [comment]
Currently the only way to achieve a multithreaded recognition operation is for each thread to have it's own instance, but I am doing some work on a local branch to make a single instance of SwiftyTesseract thread-safe.

**Comment by intellitour** [comment]
That's good news! Let us know if you need a hand.
