### ISSUE TITLE
Getting error after pod update using CocoaPods 1.7.4

### ISSUE THREAD

**Issue by christiankm** [SwiftyTesseract/SwiftyTesseract#41]
For our project we wanted to upgrade the Lottie-library, and noticed there was a new CocoaPods version 1.7.4.
So I installed that and ran pod update.

After that, our project is no longer building, and we're getting an error from the SwiftyTesseract lib, even though we didn't update or change that. We're running v2.2.0.
It does apparently not work either when using CocoaPods 1.5.3.
![Screenshot 2019-07-18 at 13 19 59](https://user-images.githubusercontent.com/3626094/61453820-6e5bad80-a95f-11e9-9d18-5b7cba1ac158.png)

**Comment by christiankm** [comment]
It could also be related to this warning I get when running pod update in our particular project:

[!] The `<TARGET_NAME>` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-<TARGET_NAME>/Pods-<TARGET_NAME>.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by christiankm** [comment]
The problem has been resolved.
Turns out I was building the SwiftyTesseract Pod Target with Swift 5 which it does not yet support. Changing Swift Version on that target to Swift 4.2 has fixed it.

**Comment by Steven0351** [comment]
Thank you for opening the issue and also taking the initiative to figure out the issue and report your findings for others to benefit!
