### ISSUE TITLE
Exporting Framework Error

### ISSUE THREAD

**Issue by mihailsalari** [SwiftyTesseract/SwiftyTesseract#43]
Hello,
How to export this framework with included libraries?
I tried few methods but I'm receiving this error while the sdk is imported in any class:
`Missing required modules: 'libleptonica', 'libtesseract'`

**Comment by Steven0351** [comment]
How are you pulling in the library. The only reason why this would happen is if the modulemap was unable to be located by the search paths so I’m guessing you’re not using one of the supported dependency management tools like Carthage or Cocoapods

**Comment by alexandrubeck** [comment]
Well, I was thinking to package the framework and deliver it without cocoapods or carthage. But at the final I'm steel blocking on that.

**Comment by Steven0351** [comment]
Is there a technical reason that Carthage is unable to be used? I really can’t support some custom implementation of the project, that’s “at your own risk” territory

**Comment by alexandrubeck** [comment]
I know, I saw you used modulemap and I thought you can help with delivery of the final framework.

**Comment by mihailsalari** [comment]
Thanks
