### ISSUE TITLE
Pod Target Swift 4.2

### ISSUE THREAD

**Issue by arrrrny** [SwiftyTesseract/SwiftyTesseract#46]
Hi,
I implemented your library in my [flutter plugin](https://pub.dev/packages/tesseract_ocr). I have to manually set the Swift version in pod file as below. Can you please specify pod_target_xcconfig = { 'SWIFT_VERSION' => '4.2' } on your plugin, so that I don't have to ask users to add below setting?
Thanks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "SwiftyTesseract"
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end

**Comment by Steven0351** [comment]
Version 2.2.2 of the CocoaPod addresses this issue. Please let me know if that didn't end up working.

**Comment by arrrrny** [comment]
Awesome! works great.
