### ISSUE TITLE
MacCatalyst compatible lib

### ISSUE THREAD

**Issue by mmilen** [SwiftyTesseract/SwiftyTesseract#51]
Hi,

Thank you very much for the great library. Any plans to release a MacCatalyst version?

**Comment by Steven0351** [comment]
Not likely. As far as any ongoing development of this library I’m mostly limiting it to bug fixes. I would suggest looking at Apple’s OCR in the Vision framework: https://developer.apple.com/documentation/vision/vnrecognizetextrequest
