### ISSUE TITLE
Language data source protocol

### ISSUE THREAD

**Issue by Minitour** [SwiftyTesseract/SwiftyTesseract#55]
After briefly inspecting the code I noticed that all the traindata files must be included within the application bundle. These files can range from few kilobytes to dozens of megabytes. 

My suggestion is, that instead of having a bundle passed as a parameter for the location of the files, there will be a protocol, (aka) data source, which developers can implement to load the tessdata files from any location they want. 

This will allow us to download models based on the user's needs. For example, users living in Canada may need only the English and French models, but people living in Israel may only need the Hebrew and Arabic models.

For example:
```swift
protocol LanguageModelDataSource {
    var pathToTrainedData: String
}
```

```swift
extension Bundle: LanguageModelDataSource {
    var pathToTrainedData: String {
          return bundleURL.appendingPathComponent("tessdata").path
    }
}
```

```swift
class MyCustomDirectoy: LanguageModelDataSource {
    var pathToTrainedData: String {
          let documentsFolderURL = try FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
         return documentsFolderURL.appendingPathComponent("tessdata").path
    }
}
```

**Comment by Minitour** [comment]
I can make a PR with this change, but only if you choose to accept this suggestion.

**Comment by Steven0351** [comment]
I do believe there is a Tesseract specific reason why everything had to be in the bundle. **However**, it's been like two years since I dealt with that problem, so if you want to tackle this and it works I'm all for it!

**Comment by Minitour** [comment]
@Steven0351  I got it to work  😄
