### ISSUE TITLE
Missing Modules Lib tesseract and Lib leptonica

### ISSUE THREAD

**Issue by itsmenaveenkumarp** [SwiftyTesseract/SwiftyTesseract#59]
I build and successfully run one simple app by downloading swiftytesseract and after that I shared code with my team and when they open my code they found following error

"required  modules lib tesseract and lib leptonica"

This is happening with everyone, Its a critical issue

Are we missing anything ?

**Comment by Steven0351** [comment]
Please use the bug issue template for issues of this nature.
