### ISSUE TITLE
Support iOS 9.0

### ISSUE THREAD

**Issue by HTKT** [SwiftyTesseract/SwiftyTesseract#6]
Can I build the lib with ios 9.0 ?

**Comment by Steven0351** [comment]
I’ll look into 9.0 compatibility; originally the library was going to use features introduced in iOS 10.0 but this restriction may no longer be necessary.

**Comment by Steven0351** [comment]
This shouldn't be a problem, I just need to recompile all the dependencies to target the lower iOS version(s).

**Comment by HTKT** [comment]
Hi @Steven0351 : Have you recompile with lower iOS version ?

**Comment by Steven0351** [comment]
Not yet, I'm having issues with the linker. I'll close the issue when I'm
able to get it figured out.

**Comment by HTKT** [comment]
Hi @Steven0351 : When can i use this lib on iOS 9? I've just tried to install your new merged for ios 9 support on Pod but it shown the error:

> [!] CocoaPods could not find compatible versions for pod "SwiftyTesseract":
>   In Podfile:
>     SwiftyTesseract
> 
> Specs satisfying the `SwiftyTesseract` dependency were found, but they required a higher minimum deployment target.

**Comment by Steven0351** [comment]
This is good to go now!

**Comment by HTKT** [comment]
i still got the error: 
[!] CocoaPods could not find compatible versions for pod "SwiftyTesseract":
  In Podfile:
    SwiftyTesseract

Specs satisfying the `SwiftyTesseract` dependency were found, but they required a higher minimum deployment target.

**Comment by Steven0351** [comment]
Paste your podfile and podfile.lock contents

**Comment by HTKT** [comment]
> Pod file:

#platform :ios, '9.0'

target 'Traversal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  # Pods for Traversal
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'SDWebImage'
  pod 'TPKeyboardAvoiding'
  pod 'KVNProgress'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Toast'
  pod 'iOS-Slide-Menu'
  pod 'CHTCollectionViewWaterfallLayout'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Google/SignIn'
  pod 'IQActionSheetPickerView'
  pod 'GLCalendarView'
  pod 'SkyFloatingLabelTextField'
  pod 'SwiftyTesseract'

end

> Podfile.lock

PODS:
  - AFNetworking (3.1.0):
    - AFNetworking/NSURLSession (= 3.1.0)
    - AFNetworking/Reachability (= 3.1.0)
    - AFNetworking/Security (= 3.1.0)
    - AFNetworking/Serialization (= 3.1.0)
    - AFNetworking/UIKit (= 3.1.0)
  - AFNetworking/NSURLSession (3.1.0):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (3.1.0)
  - AFNetworking/Security (3.1.0)
  - AFNetworking/Serialization (3.1.0)
  - AFNetworking/UIKit (3.1.0):
    - AFNetworking/NSURLSession
  - Bolts (1.8.4):
    - Bolts/AppLinks (= 1.8.4)
    - Bolts/Tasks (= 1.8.4)
  - Bolts/AppLinks (1.8.4):
    - Bolts/Tasks
  - Bolts/Tasks (1.8.4)
  - CHTCollectionViewWaterfallLayout (0.9.5):
    - CHTCollectionViewWaterfallLayout/ObjC (= 0.9.5)
  - CHTCollectionViewWaterfallLayout/ObjC (0.9.5)
  - Crashlytics (3.8.6):
    - Fabric (~> 1.6.3)
  - Fabric (1.6.11)
  - FBSDKCoreKit (4.22.1):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.22.1):
    - FBSDKCoreKit
  - FirebaseAnalytics (3.9.0):
    - FirebaseCore (~> 3.6)
    - FirebaseInstanceID (~> 1.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseCore (3.6.0):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseInstanceID (1.0.10):
    - FirebaseCore (~> 3.6)
  - GLCalendarView (1.2.1)
  - Google/Core (3.0.3):
    - FirebaseAnalytics (~> 3.2)
  - Google/SignIn (3.0.3):
    - Google/Core
    - GoogleSignIn (~> 4.0)
  - GoogleSignIn (4.0.2):
    - "GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
    - "GoogleToolboxForMac/NSString+URLArguments (~> 2.1)"
    - GTMOAuth2 (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleToolboxForMac/DebugUtils (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - GoogleToolboxForMac/Defines (2.1.1)
  - "GoogleToolboxForMac/NSData+zlib (2.1.1)":
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - "GoogleToolboxForMac/NSDictionary+URLArguments (2.1.1)":
    - GoogleToolboxForMac/DebugUtils (= 2.1.1)
    - GoogleToolboxForMac/Defines (= 2.1.1)
    - "GoogleToolboxForMac/NSString+URLArguments (= 2.1.1)"
  - "GoogleToolboxForMac/NSString+URLArguments (2.1.1)"
  - GTMOAuth2 (1.1.4):
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.1.10):
    - GTMSessionFetcher/Full (= 1.1.10)
  - GTMSessionFetcher/Core (1.1.10)
  - GTMSessionFetcher/Full (1.1.10):
    - GTMSessionFetcher/Core (= 1.1.10)
  - iOS-Slide-Menu (1.5)
  - IQActionSheetPickerView (2.0.0)
  - JSONModel (1.7.0)
  - KVNProgress (2.3.1)
  - SDWebImage (4.0.0):
    - SDWebImage/Core (= 4.0.0)
  - SDWebImage/Core (4.0.0)
  - SkyFloatingLabelTextField (3.4.1)
  - Toast (3.1.0)
  - TPKeyboardAvoiding (1.3.1)

DEPENDENCIES:
  - AFNetworking
  - CHTCollectionViewWaterfallLayout
  - Crashlytics
  - Fabric
  - FBSDKCoreKit
  - FBSDKLoginKit
  - GLCalendarView
  - Google/SignIn
  - iOS-Slide-Menu
  - IQActionSheetPickerView
  - JSONModel
  - KVNProgress
  - SDWebImage
  - SkyFloatingLabelTextField
  - Toast
  - TPKeyboardAvoiding

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - AFNetworking
    - Bolts
    - CHTCollectionViewWaterfallLayout
    - Crashlytics
    - Fabric
    - FBSDKCoreKit
    - FBSDKLoginKit
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseInstanceID
    - GLCalendarView
    - Google
    - GoogleSignIn
    - GoogleToolboxForMac
    - GTMOAuth2
    - GTMSessionFetcher
    - iOS-Slide-Menu
    - IQActionSheetPickerView
    - JSONModel
    - KVNProgress
    - SDWebImage
    - SkyFloatingLabelTextField
    - Toast
    - TPKeyboardAvoiding

SPEC CHECKSUMS:
  AFNetworking: 5e0e199f73d8626b11e79750991f5d173d1f8b67
  Bolts: 8a7995239dbe724f9cba2248b766d48b7ebdd322
  CHTCollectionViewWaterfallLayout: 775ff73f48cfc13859b62d8bceb96e772e4a0318
  Crashlytics: 95d05f4e4c19a771250c4bd9ce344d996de32bbf
  Fabric: 5911403591946b8228ab1c51d98f1d7137e863c6
  FBSDKCoreKit: 9c2daf0162214d6d2e21cf8208a9c6c2a2e42b9c
  FBSDKLoginKit: 00cf28916b9f0169763a3d61985d745b579fe304
  FirebaseAnalytics: e5fe8486efc01bec33f6bf82e2fa9fce4b124052
  FirebaseCore: 9691ee2ade70c098d7cf92440f4303f16d83ca75
  FirebaseInstanceID: b9eedd6846fb5e1f0f7279e1deaa7a7e4cf8392e
  GLCalendarView: 9d0be9a332bc09f556a79600a0d2d1404806f719
  Google: cd92fab98f800f509da88c1e0c570275713bc9d5
  GoogleSignIn: d7ad83f13480e1f30453471d00d19b5293ac46af
  GoogleToolboxForMac: 8e329f1b599f2512c6b10676d45736bcc2cbbeb0
  GTMOAuth2: 7fc9c10f5c745f4d9850419ea88889fe3baa6b7d
  GTMSessionFetcher: 30d874b96d0d76028f61fbd122801e3f030d47db
  iOS-Slide-Menu: 40b0cbd8916c42afc755f0869793cd09e7a32102
  IQActionSheetPickerView: 7986373d485f144589eec2c7c3014645c885f38b
  JSONModel: 840bc0fcffb24b8454d2c026bf26fea454b8e98d
  KVNProgress: 8167b1f19e2758290c0b6143020ed9dcbb0477a1
  SDWebImage: 76a6348bdc74eb5a55dd08a091ef298e56b55e41
  SkyFloatingLabelTextField: 8085f20f57f74a00cfcae58099299faa1a971035
  Toast: 14a93686d6c8bfe2727afd342414e35660a8a1f3
  TPKeyboardAvoiding: 0d6af20e95e2850f4c621841225b59ec7d8dd852

PODFILE CHECKSUM: 9c056db4f6f519f99c76b32920f90334df9e80e6

COCOAPODS: 1.5.0

**Comment by Steven0351** [comment]
The current version is 1.1.1 as can be seen by the version tag in the readme (which is directly linked from cocoapods, that’s not something that I create). Either explicitly specify 1.1.1 or reinstall cocoapods so it updates the master spec repo

**Comment by Steven0351** [comment]
Another user had a similar issue on #7 and performed the following to update their cocopods repo:

>Solved. FYI.
>Steve,
>I already had latest CocoaPods. BUT ( a big BUT) after the typicall "sudo gem install cocoapods" you need to update pod with "pod setup" ... and solved.
>thanks!!!

**Comment by HTKT** [comment]
Thanks @Steven0351 much. It worked fine now 👍
