### ISSUE TITLE
required module missing libtesseract libleptionica always

### ISSUE THREAD

**Issue by itsmenaveenkumarp** [SwiftyTesseract/SwiftyTesseract#60]
**required module missing libtesseract libleptionica **
"required module missing libtesseract libleptionica",Clone the swiftytesseract repo and build it, then took the .framework file and I used in my blank project which just gives image and uses tesseract code.

**To Reproduce**
clone or download the zip file build it and take swiftytesseract.framework. Add this in-app code and build it and run then app will work. Now distribute this code to another development MacBook and build your app it will throw an error saying "required module missing libtesseract libleptionica".
This is happening with every developer (34+ developers )

**Expected behaviour**
Once any app build with embed & sign (swiftytesseract.framework) same code should work on all the machines instead of throwing error for all.

**Versions**
* Xcode: 11.3.1
* Swift: 5.1
* iOS: 13.2
* SwiftyTesseract:2.2.0 and latest version

**Dependency Management**
Are you using CocoaPods or Carthage? What version?
Tried with CocoaPods and error exist

**Additional context**
Every time developer needs to clone this repo and build code then take ".framework" file to make it work. it's so horrible

**Comment by Steven0351** [comment]
Pasting your email here:
Hope you are doing well, 
Its a  pleasure to e-meet you, I am a big fan of swifty tesseract ios version. Thanks for creating such cool libraries.

I have noticed one issue though, once i download swifty tesseract and build it in my computer then I can run my code, but if I shared the same with my development team none of them able to use it. It keeps on throwing "Missing required module libtesseract libleptonica" I hope once u download and run the attached sample code you also will get same error. Please help,  i have to complete one delivery so kind of stuck here. 

Please check my sample code, which just load image and return ocr data.

-- Link omitted --
I've removed the link from this email

**Comment by itsmenaveenkumarp** [comment]
Can u post any solution ?

**Comment by Steven0351** [comment]
To clarify, it seems that you are building this binary on your machine and then sharing it with others? I do not, will not, and cannot support any use of this outside of Cocoapods or Carthage. I've gone down this road before and ended up spending significant amount of time helping people with non-standard build configurations to find that it was an issue with their custom build configuration (i.e. not using Cocoapods or Carthage). The sample code you provided me included a pre-built binary, with no Cocoapods or Carthage configuration. If you insist on building SwiftyTesseract outside of Cocoapods or Carthage as part of your routine build, you are unfortunately on your own. If you can find a fix, you are more than welcome to open a PR.

**Comment by itsmenaveenkumarp** [comment]
In Cocoapods, it will show the same error, I tried that also

**Comment by Steven0351** [comment]
Please provide sample code using cocoapods then

**Comment by itsmenaveenkumarp** [comment]
Yeah i can give, but this is a big issue in module mapping and am wondering why no one raised yet

**Comment by itsmenaveenkumarp** [comment]
Here is the pod sample code link
[Link](https://www.dropbox.com/s/5jwmdckokormtbo/swiftMRzpod.zip?dl=0
)and here is the Stackoverflow link of this issue
[Link](https://stackoverflow.com/questions/61422594/missing-required-modules-libtesseract-libleptonica)

**Comment by Steven0351** [comment]
![Screen Shot 2020-04-25 at 2 23 44 PM](https://user-images.githubusercontent.com/24440751/80288841-6146c880-8700-11ea-8373-46c3975d6e40.png)
I downloaded your sample code, built and ran, with zero issue

**Comment by itsmenaveenkumarp** [comment]
SwiftyTesseract never works if i added it inside a customer framework project, it only work for Single View Applications

**Comment by Steven0351** [comment]
I am going to _reiterate_ what I have said over and over again: If your project is not using Cocoapods or Carthage as a dependency manager for your product, I am not supporting it. I'm not interested in supporting your very specific use-case for your enterprise when you have shown zero initiative in looking into the issue yourself. If it's important for your enterprise to use this project, then spend time on improving it for your use case and contribute back to the project, I will not be doing it for you.
