### ISSUE TITLE
App crashes with terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

### ISSUE THREAD

**Issue by m-aazhar** [SwiftyTesseract/SwiftyTesseract#67]
My app crashes with error :*** mach_vm_map(size=1566588928, flags: 100) failed (error code=3)
checksAnsCardsbyAIrDemo(1609,0x1009ed840) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

**Comment by Steven0351** [comment]
Please open a new issue using one of the [templates](https://github.com/SwiftyTesseract/SwiftyTesseract/issues/new/choose) provided.
