### ISSUE TITLE
recogin very slow

### ISSUE THREAD

**Issue by lihualin1688** [SwiftyTesseract/SwiftyTesseract#68]
when I run the demo to recogin chinese char, it's very slow!!

**Comment by Steven0351** [comment]
https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md#opening-issues

**Comment by Steven0351** [comment]
Aside from you ignoring the two issue templates that come up as options, the performance of the actual recognition operation has to do with Tesseract itself, not this project. This library is merely a wrapper over that. If you have any issues with the behavior of Tesseract you should raise your issues there: https://github.com/tesseract-ocr/tesseract/issues
