### ISSUE TITLE
[!] Unable to find a specification for `SwiftyTesseract (~> 1.0)`

### ISSUE THREAD

**Issue by iguron** [SwiftyTesseract/SwiftyTesseract#7]
Hi,

I´m facing a problem installing SwiftyTesseract with CocoaPods.

[!] Unable to find a specification for `SwiftyTesseract (~> 1.0)`

Any solution??

Thanks in advance.

**Comment by Steven0351** [comment]
Can you paste your Podfile data? SwiftyTesseract needs to be included in the Podfile like this:
```ruby
pod 'SwiftyTesseract',    '~> 1.0'
```
or alternatively:
```ruby
pod 'SwiftyTesseract'
```

The CI build is executing flawlessly and I had no issues running the Podfile as I've outlined below.

**Comment by iguron** [comment]
Hi, thanks for the quick answer.

I tried in both ways.

This is my podfile

# Uncomment the next line to define a global platform for your project
use_frameworks!
platform :ios, '10.0'

target 'MyApp' do
  use_frameworks!
  pod 'Fuse'
  pod 'SwiftyTesseract',    '~> 1.0'
end

**Comment by iguron** [comment]
Hi,

I test it again with the same problem. I tried both ways described below.

**Comment by iguron** [comment]
FYI.

pod 'SwiftyTesseract', :git => 'https://github.com/SwiftyTesseract/SwiftyTesseract.git'

works!!!

**Comment by Steven0351** [comment]
Your Cocoapods may not be up to date with the latest repositories. Try running
```bash 
$ sudo gem install cocoapods
```

**Comment by iguron** [comment]
Solved. FYI.

Steve,

I already had latest CocoaPods. BUT ( a big BUT) after the typicall "sudo gem install cocoapods" you need to update pod with "pod setup" ... and solved.

thanks!!!

**Comment by Steven0351** [comment]
Awesome, thanks for sharing the fix!
