### ISSUE TITLE
Does it support video to scan the text?

### ISSUE THREAD

**Issue by MarcSteven** [SwiftyTesseract/SwiftyTesseract#71]
### Checklist
- [] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steven0351** [comment]
https://github.com/SwiftyTesseract/SwiftyTesseractRTE might have what you need, but I haven’t updated it for Swift 5.0 as I don’t really use it much anymore.
