### ISSUE TITLE
Unable to install iOS application on device

### ISSUE THREAD

**Issue by ViktorSimko** [SwiftyTesseract/SwiftyTesseract#75]
### Checklist
- [x] I've read the [Readme](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/README.md)
- [x] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [x] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).
- [] I'm using Cocoapods  for dependency management
- [] I'm using Carthage  for dependency management

**Describe the bug**
I get the following error using SwiftPM in Xcode for an iOS project, while installing the app.

```
Details

Unable to install "<app name>"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011f83190f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000011f8700f4 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x00000001029bccef DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000011f86fe35 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000011f6e0d84 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000102aeb45a __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000102aed07c __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff20d5d52d _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff20d5e717 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff20d6454e _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff20d6501b _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff20d6eb9b _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff20ea44f2 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff20ea34c3 start_wqthread + 15
);
}
--


System Information

macOS Version 11.0 (Build 20A5364e)
Xcode 12.0 (17210.1)
```

**Expected behavior**
The application should install and run on the device.

**Versions**
* Xcode: 12.0 (17210.1)
* Swift: 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)
* iOS: 14.0 (18A5373a)
* SwiftyTesseract: develop branch

**Comment by Steven0351** [comment]
Are you code signing your application? I see nothing in that stack trace that would point to SwiftyTesseract being the issue there

**Comment by Steven0351** [comment]
https://stackoverflow.com/questions/58983562/xcode-cant-install-application

**Comment by ViktorSimko** [comment]
Yes, I'm code signing the app.
I'm pretty sure the issue is with SwiftyTesseract because if I remove it from the Swift packages, the app installs successfully.

**Comment by ViktorSimko** [comment]
If anyone runs into this, here is how to resolve the issue: [https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/](https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/)
