### ISSUE TITLE
custom traineddata error

### ISSUE THREAD

**Issue by nemno** [SwiftyTesseract/SwiftyTesseract#76]
### Checklist
- [x] I've read the [Readme](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/README.md)
- [x] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [x] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).
- [x] I'm using Cocoapods  for dependency management
- [ ] I'm using Carthage  for dependency management

**Describe the bug**

The custom mrz traineddata part sais:
For example, if you wanted to use the MRZ code optimized OCRB.traineddata file provided by Exteris/tesseract-mrz, the instance of Tesseract would be created like this:

if I use the file from the linked repo like this:
SwiftyTesseract(language: .custom("OCRB"), dataSource: Bundle(identifier: "xxx") ?? Bundle(for: yyy.self), engineMode: .lstmOnly)

the following error is the result:

Error: LSTM requested, but not present!! Loading tesseract.

I tried the original traineddata files from tessdata folder: eng, hun

SwiftyTesseract(language: .custom("eng"), dataSource: Bundle(identifier: "xxx") ?? Bundle(for: yyy.self), engineMode: .tesseractLstmCombined)

those are OK.

**Sample Code**

**Expected behavior**

**Versions**
* Xcode: 11.7
* Swift: 5
* iOS: 13.6
* SwiftyTesseract: 3.1.2

**Additional context**

**Comment by Steven0351** [comment]
That log is just from tesseract saying that the training file does not support LSTM and is loading the legacy tesseract engine. This is expected behavior for a training file not created for the LSTM engine.

**Comment by nemno** [comment]
ah. thanks for the quick reply.
