### ISSUE TITLE
SPM implementation gets rejected by AppStore

### ISSUE THREAD

**Issue by GabiGVeesto** [SwiftyTesseract/SwiftyTesseract#83]
### Checklist
- [x] I've read the [Readme](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/README.md)
- [x] I've read the [Contribution Guidelines](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CONTRIBUTING.md)
- [x] I've read the [Code of Conduct](https://github.com/SwiftyTesseract/SwiftyTesseract/blob/master/CODE_OF_CONDUCT.md).
- [] I'm using Cocoapods  for dependency management
- [] I'm using Carthage  for dependency management
- [x] I'm using SPM  for dependency management
- 
**Describe the bug**
I've implemented the Swift package version of the library, added the package to the project just as instructed,
When trying to upload my app to the AppStore it gets rejected with the following Error - 
"The binary file 'XYZ.app/Frameworks/libtesseract.framework/libtesseract' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles."

**Sample Code**

**Expected behavior**
A successful upload to the AppStore

**Versions**
* Xcode: 12.3(12C33)
* Swift: 5
* iOS: 12+
* SwiftyTesseract: 4.0.0

**Additional context**
None

**Comment by Steven0351** [comment]
This is a known issue with a workaround discussed in https://github.com/SwiftyTesseract/libtesseract/issues/3

**Comment by Steven0351** [comment]
There's also some additional information here as well: https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/

This seems more to do with binary swift packages than anything, but I should probably add something near the top of the README until this is resolved by Apple. They use libswiftpm and I believe this is more in how they've implemented the integration in Xcode.

**Comment by GabiGVeesto** [comment]
> This is a known issue with a workaround discussed in [SwiftyTesseract/libtesseract#3](https://github.com/SwiftyTesseract/libtesseract/issues/3)

Didn't solve the issue, 
When trying to submit to AppStore I'm still getting this:

_**"The binary file 'XYZ.app/Frameworks/libtesseract.framework/libtesseract' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles."**_

Tried to remove the framework file manually from the archive and it **did upload with success**, but then I got an Email from apple that there was an error - 
**_"ITMS-90000: This bundle is invalid - $message."_**

Tried to add a run script on the 'Post Archive' action in the build scheme but no luck...

**Comment by Steven0351** [comment]
The issue I linked has them removing it pre-archive in a run script phase at the end of their build phases. I think your issue doing it post archive is that the bundle you are uploading it has the framework in the manifest and when App Store connect does its post-upload processing it sees that it’s missing. Please try following their fix by adding it to a run script phase during the build instead of post archive.

**Comment by GabiGVeesto** [comment]
I've tried putting that run script as the last build phase, didn't work.

I think maybe it has something to do with the path in the script - $CODESIGNING_FOLDER_PATH 
The error from the submit states it's in the framework path so maybe $CODESIG... points to the wrong path for this case?

I'll try again with -
${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}

**Comment by Steven0351** [comment]
That could be the case, that person was building for macOS. The framework path seems more plausible in this case

**Comment by GabiGVeesto** [comment]
> ${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}
Didn't work...
Also tried - 
`rm -rf "${CODESIGNING_FOLDER_PATH}/Frameworks/libtesseract.framework"`
in Build Phase and also Pre Archive...nothing

I made an attempt with - 
`rm -f "${CODESIGNING_FOLDER_PATH}/Frameworks/libtesseract.framework/libtesseract"`
and it removed the executable from the folder, but then when I archived it re-appeared from thin air...

What to do? Am I the only one experiencing such rejects by the AppStore?

**Comment by Steven0351** [comment]
I created a brand new app, added the dependency, added a post-action in the build phases
<img width="186" alt="Screen Shot 2021-01-14 at 4 03 40 PM" src="https://user-images.githubusercontent.com/24440751/104654658-1439c680-5682-11eb-976d-f838d98a538a.png">
and ran this: `rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/libtesseract.framework"`. The app uploaded and processed without issue.

**Comment by Steven0351** [comment]
I was also able to remove it during the build phases as well and successfully upload. Have you tried deleting derived data and trying again?

**Comment by GabiGVeesto** [comment]
> I created a brand new app, added the dependency, added a post-action in the build phases
> <img alt="Screen Shot 2021-01-14 at 4 03 40 PM" width="186" src="https://user-images.githubusercontent.com/24440751/104654658-1439c680-5682-11eb-976d-f838d98a538a.png">
> and ran this: `rm -rf "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Frameworks/libtesseract.framework"`. The app uploaded and processed without issue.

Did this, and in addition, added it also to the Build Phases, eventually this only worked when I upped the build version and deleted derived data!

Thanks a million!
