### ISSUE TITLE
Error when archiving 

### ISSUE THREAD

**Issue by HTKT** [SwiftyTesseract/SwiftyTesseract#9]
I've used the latest version which support iOS 9.0 and when archiving, the compiler return the error:
`ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '902.0.39.1_0' Reader: '900.0.39.2_0')', using libLTO version 'LLVM version 9.0.0, (clang-900.0.39.2)' for architecture armv7
`
Can you help to check this error? Thanks

**Comment by Steven0351** [comment]
Can you verify which version of Xcode you are using? This looks like a toolchain issue: the vended libraries were compiled with LLVM version 9.1.0 (clang-902.0.39.1) and it looks like the toolchain you're currently using is older. This can be fixed either by updating your toolchain/Xcode or by disabling bitcode.

**Comment by HTKT** [comment]
Thanks, i solved the issue already.

**Comment by Steven0351** [comment]
Would you mind sharing your fix?

**Comment by HTKT** [comment]
i've just update the latest XCode and try again. As you mentioned, the library is built with newer clang version.
