### ISSUE TITLE
Symbol not found: _$s15SwiftyTesseract10EngineModeO21tesseractLstmCombinedyA2CmFWC

### ISSUE THREAD

**Issue by naveen-kp-clt** [SwiftyTesseract/SwiftyTesseract#92]
Getting this issue in run time using cocoapods, how to solve this ?

dyld: Symbol not found: _$s15SwiftyTesseract10EngineModeO21tesseractLstmCombinedyA2CmFWC
  Referenced from: /private/var/containers/Bundle/Application/8B235A56-F974-48A1-B22B-B130F9C947B9/ios14.4.app/Frameworks/SIDocumentSDK.framework/SIDocumentSDK
  Expected in: /private/var/containers/Bundle/Application/8B235A56-F974-48A1-B22B-B130F9C947B9/ios14.4.app/Frameworks/SwiftyTesseract.framework/SwiftyTesseract
 in /private/var/containers/Bundle/Application/8B235A56-F974-48A1-B22B-B130F9C947B9/ios14.4.app/Frameworks/SIDocumentSDK.framework/SIDocumentSDK
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb)

**Comment by Steven0351** [comment]
Please read this next time before opening an issue: https://github.com/SwiftyTesseract/SwiftyTesseract/blob/develop/CONTRIBUTING.md. Feel free to go through the existing issue templates and paste all the required information in a comment or open a new issue.

**Comment by Steven0351** [comment]
Next time, review the readme (which states that Cocoapods is no longer supported) and contributing documentation before opening an issue and use one of the pre-existing issue templates.
